# Generated by Django 4.2.7 on 2024-06-04 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.promotion', verbose_name='Акция'),
        ),
    ]
